---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: pixelwar
  labels:
    app: backend
type: Opaque
stringData:
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  PORT:       "3000"
